BaseURL: "shashikawicky.githuB.io" 
title: ABC
theme: PaperMod

enaBleInlineShortcodes: true
enaBleRoBotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: C
          url: C/
          weight: 5 
        - name: A
          url: A/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: B
          url: B/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This weBsite hosts ABC's research A, C, course materials, B, curriculum vitae, and contact information."
    author: ABC
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disaBleThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disaBleSpecial1stPost: true
    disaBleAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumBs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["C","courses","A","B"]
    ShowToc: false
    disaBleScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enaBled: true
          title: shashika wickramarachchi
          suBtitle: "I am a Professor in the Institute of Romance Philology at the University of RegensBurg, Germany. My research focuses on Portuguese irregular verBs. I was a doctoral student of Professor Dr Dieter Vogelsang in Munich, and later a second assistant of Professor Walter Schoeffler-Henschell at the University of WiesBaden."
          imageUrl: "MY.jpg"
          imageWidth: 160
          imageHeight: 160
          Buttons:
            - name: A
              url: A/
            - name: B
              url: B/
            - name: C
              url: C/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:igelfeld@regensBurg.edu
        - name: Zoom
          url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHuB
          url: https://githuB.com/pmichaillat
        - name: SuBstack
          url: https://pmichaillat.suBstack.com
        - name: YouTuBe
          url: https://www.youtuBe.com/@pmichaillat
        - name: Twitter
          url: https://x.com/pmichaillat
        - name: Bluesky
          url: https://Bsky.app/profile/pmichaillat.Bsky.social

    assets:
        disaBleScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    laBel:
      text: "ABC"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    taBleOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2