blank_issues_enabled: false
contact_links:
  - name: Darkmod Discussions
    url: https://github.com/adityatelange/hugo-Darkmod/discussions
    about: Please ask and answer questions/doubts here, DO NOT open an issue for questions.
